---
title: "Surfing"
output:
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    orientation: rows
    theme: cosmo
    includes:
        in_header: src/g.analytics.htm
---

<style>                     
<!-- .value-box .icon .fa { -->
<!-- font-size: 180%; -->
<!-- color: rgba(255, 255, 255, 0.8); -->
<!-- top: 7px; -->
<!-- } -->
<!-- .value-box .value { -->
<!-- font-size: 23px; -->
<!-- margin: -5px 0 3px 0; -->
<!-- } -->
<!-- .value-box h6 { -->
<!-- font-size: 20px; -->
<!-- font-weight: bold; -->
<!-- margin-top: -8px; -->
<!-- } -->
<!-- .r0 { -->
<!-- margin-right: 72%; -->
<!-- } -->
<!-- .r1right { -->
<!-- margin-right: 43.4%; -->
<!-- } -->
<!-- h3 { -->
<!-- font-size:19px; -->
<!-- margin-right: 20px; -->
<!-- margin-top: 10.5px; -->
<!-- margin-bottom: 10.5px; -->
<!-- display: block; -->
<!-- font-weight: bold; -->
<!-- font-family: "Source Sans Pro",Calibri,Candara,Arial,sans-serif; -->
<!-- line-height: 1.1; -->
<!-- color: inherit; -->
<!-- } -->
<!-- .navbar{ -->
<!--   visibility: hidden -->
<!-- } -->
<!-- body { -->
<!--     padding-top: 10px; -->
<!-- } -->

.section.sidebar {
  top: 61px;
  border-bottom: 10px solid #ececec;
  border-left: 10px solid #ececec;
  background-color: rgba(255, 255, 255, 1);
}

<!-- #map{ -->
<!--   position: absolute; -->
<!--   top: 0; -->
<!--   bottom: 0; -->
<!--   width: 100%; -->
<!-- } -->
</style>


```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(RColorBrewer)
library(flexdashboard)
library(shiny)
library(zoo)
library(leaflet)
library(XML)
library(geosphere)
library(RColorBrewer)
library(fit)
```

```{r}
# load function
# https://rdrr.io/cran/plotKML/src/R/readGPX.R
source("src/readGPX.R")
source("src/readTCX.R")
```

```{r}
getDatefromTimestamp <- function(tstmp){
   t <- as.POSIXct(tstmp, origin="1989-12-31",tz="UTC")
   t <- paste0(str_replace(t, " ","T"),".000Z")
   return(t)
}
```


```{r}
# read file
#gpx <- readGPX("data/surfing.GPX")
gpx <- readGPX("data/surf_gunnamata_201115.gpx")
gpx <- readGPX("SURFING_POLAR/surfing_polar_2021-10-26T15-00-19.gpx")
gpx <- gpx$tracks[[1]][[1]]
tcx <- readTCX('data/Sergio_Ruiz_2022-04-25_11-33-04.TCX')
fitdata <- read.fit('data/ninasurf.fit')
# head(fitdata$record)
gpx <- fitdata$record %>% 
  # head() %>% 
  select(lat=position_lat,
         lon=position_long,
         time = timestamp) %>% 
  mutate(time = getDatefromTimestamp(time)) %>% 
  drop_na()
gpx <- tcx %>% 
  select(lat=LatitudeDegrees,
         lon=LongitudeDegrees,
         time=Time) %>% 
  drop_na()


# head(gpx)
```

```{r}
gpx <- gpx %>%
  mutate(date=ifelse(is.na(format(as.POSIXct(time,format="%Y-%m-%dT%H:%M:%SZ",tz="UTC"),
                                  tz="Australia/Melbourne")),
                     format(as.POSIXct(time,format="%Y-%m-%dT%H:%M:%S.000Z",tz="UTC"),
                            tz="Australia/Melbourne"),
                     format(as.POSIXct(time,format="%Y-%m-%dT%H:%M:%SZ",tz="UTC"),
                            tz="Australia/Melbourne")),
         day=format(as.POSIXct(date),"%y%m%d"),
         timeofday=format(as.POSIXct(date),"%H:%M:%S"),
         time_posix = time, 
         time=ifelse(is.na(as.POSIXct(time,format="%Y-%m-%dT%H:%M:%SZ",tz="UTC")),
                     as.POSIXct(time,format="%Y-%m-%dT%H:%M:%S.000Z",tz="UTC"),
                     as.POSIXct(time,format="%Y-%m-%dT%H:%M:%SZ",tz="UTC"))
                           ) %>%
  select(-date,-one_of("ele"),-day)
```

```{r}
# get distance and remove the steps with 0
gpx <- gpx %>% 
  mutate(laglon=lag(lon),
         laglat=lag(lat)) %>% 
  rowwise() %>%
  mutate(step_distance=distm(c(lon,lat),c(laglon,laglat),fun=distHaversine)) %>% 
  ungroup() %>% 
  mutate(step_distance=as.numeric(step_distance),
         cum_distance=round(cumsum(replace_na(step_distance,0)),2)) %>% 
  select(-laglon,-laglat) %>% 
  filter(step_distance != 0)

# get step time
gpx <- gpx %>% 
  mutate(step_s=as.numeric(time-lag(time)),
         step_s=case_when(
           is.na(step_s) ~ 1,
           step_s > 15 | lag(step_s,n=1) > 15 | lag(step_s,n=2) > 15 | lag(step_s,n=3) > 15  ~ rollmean(x=step_s,4,align="right",fill=NA),
           step_s > 10 | lag(step_s,n=1) > 10 | lag(step_s,n=2) > 10 ~ rollmean(x=step_s,3,align="right",fill=NA),
           step_s > 5 | lag(step_s,n=1) > 5 | lag(step_s,n=2) > 5 ~ rollmean(x=step_s,2,align="right",fill=NA),
           TRUE ~ round(step_s,2)
         ),
         cum_s=cumsum(replace_na(step_s,0)),
         cum_min=round(cum_s/60,2))
```


```{r}
# speed
gpx <- gpx %>% 
  mutate(speed.raw=(step_distance/1000)/(step_s/3600),
         speed=case_when(
           row_number() <= 10 ~ rollmean(x=speed.raw, 5, align="left",fill=NA),
           TRUE ~ rollmean(x=speed.raw, 5,  align="right",fill=NA))
         )
```

```{r}
wave <- gpx %>% 
  # slice(c(1:500)) %>% 
  select(-speed.raw,-time, -time_posix, -step_distance)

min.speed <- 7
min.speedmax <- 13
max.speed <- 40 # for speed errors with GPS
min.length <- 6
# #urbnsurf settings
min.speed <- 7
min.speedmax <- 11
max.speed <- 40 # for speed errors with GPS
min.length <- 6

wave <- gpx %>% 
  mutate(wave.speed = ifelse(speed > min.speed,1,0)) %>% 
  mutate(wave.length = ifelse(wave.speed == 1 &
           (lag(wave.speed,n=5,default=0)+
           lag(wave.speed,n=4,default=0)+
           lag(wave.speed,n=3,default=0)+
           lag(wave.speed,n=2,default=0)+
           lag(wave.speed,n=1,default=0)+
           wave.speed+
           lead(wave.speed,n=1,default=0)+
           lead(wave.speed,n=2,default=0)+
           lead(wave.speed,n=3,default=0)+
           lead(wave.speed,n=4,default=0)+
           lead(wave.speed,n=5,default=0)) >= min.length,
           1,0)) %>%
  mutate(wave.n = ifelse(wave.speed != lag(wave.speed,default=0) & wave.speed == 1 & wave.length == 1,1,0)) %>%
  mutate(wave.n = ifelse(wave.speed == 1 & wave.length == 1,cumsum(replace_na(wave.n,0)),0)) %>%
  # filter(wave.speed !=0) %>% 
  group_by(wave.speed,wave.length,wave.n) %>%
  mutate(wave.speedcheck = case_when(
    any(wave.speed == 1 & wave.length==1 & speed > min.speedmax) & !any(speed.raw > max.speed & speed > min.speedmax) ~ 1,
    # any(wave.speed == 1 & wave.length==1 & speed > min.speedmax) ~ 1,
    TRUE ~ 0)) %>%
  ungroup() %>%
  mutate(wave.n = ifelse(wave.speed != lag(wave.speed,default=0) & wave.speed == 1 & wave.length == 1 & wave.speedcheck == 1,1,0)) %>%
  mutate(wave.n = ifelse(wave.speed == 1 & wave.length == 1 & wave.speedcheck == 1,cumsum(replace_na(wave.n,0)),0)) %>%
  data.frame()
# wave
# wave <- wave %>% filter(wave.n != 0)
# wave
# max(wave$wave.n)
# plot(wave$cum_distance,wave$speed,type="l")
```

```{r}
mycols <- c("#000000",brewer.pal(n = 8, name = "Dark2"))
mycols <- c("#000000",rainbow(max(wave$wave.n)))
points <- wave %>% select(lat,lon,speed,wave.n) %>%  filter(wave.n != 0)
```

```{r}
# newcols <- rev(cet_pal(min(dim(points)[1],256),name="l3"))
points1 <- points %>%
  group_by(wave.n) %>% 
  mutate(nextLat = lead(lat),
         nextLng = lead(lon),
  ) %>% 
  ungroup() %>% 
  mutate(color=mycols[-1][as.factor(wave.n)])
# points1
# ProviderTiles
# https://leaflet-extras.github.io/leaflet-providers/preview/index.html
gradient_map <- leaflet(width="100%") %>%
  addTiles()
  # addProviderTiles(providers$Stamen.Watercolor) %>%
  # addProviderTiles(providers$Stamen.TonerHybrid) %>% 
  # addProviderTiles(providers$Thunderforest.OpenCycleMap)
for (i in 1:nrow(points1)) {
  gradient_map <- addPolylines(map = gradient_map,
                               data = points1,
                               opacity = 1,
                               weight=8,
                               # polyline = 'route',
                               # smoothFactor = 0,
                               lng = as.numeric(points1[i, c('lon', 'nextLng')]),
                               lat = as.numeric(points1[i, c('lat', 'nextLat')]),
                               color = as.character(points1[i, c('color')])
  )
}
```

```{r}
start <- points1 %>% group_by(wave.n) %>% filter(row_number() == 1)
end <- points1 %>% group_by(wave.n) %>% mutate(lat=last(lat),lon=last(lon)) %>% filter(row_number() == 1)

testmap <- gradient_map %>% setView(start[1,'lon'],start[1,'lat'],zoom=15)
for (i in 1:nrow(start)) {
  testmap <- addCircleMarkers(map=testmap,
                        lng=as.numeric(end[i,'lon']),
                        lat=as.numeric(end[i,'lat']),
                        weight = 2, radius= 5,
                        opacity=1,
                        fillColor='black',
                        fillOpacity = 0.2,
                        color='black'
  )
  testmap <- addCircleMarkers(map=testmap,
                              lng=as.numeric(start[i,'lon']),
                              lat=as.numeric(start[i,'lat']),
                              weight = 2, radius= 5,
                              opacity=1,
                              fillColor='white',
                              fillOpacity = 0.7,
                              color='black', label=i,
                              labelOptions = labelOptions(noHide = T, textOnly = T,sticky=F,direction="right",
                                                          textsize = "20px", offset = c(5,0),
                                                          style=list(
                                                            "font-weight"="bold"
                                                          ))
  )
}
wave1 <- points1 %>% filter(wave.n == 1)
```


```{r}
session <- gpx %>% 
  mutate(time = format(as.POSIXct(time_posix,format="%Y-%m-%dT%H:%M:%S.000Z",tz="UTC"),
                       tz="Australia/Melbourne","%y/%m/%d-%H:%M")) %>% 
  filter(row_number() == 1) %>% 
  select(time)
# time <- format(as.POSIXct(gpx$time[1],format="%Y-%m-%dT%H:%M:%S.000Z",tz="UTC"),tz="Australia/Melbourne","%y/%m/%d-%H:%M")
session$nwaves <- max(wave$wave.n)
# session$totaltime.min <- gpx %>% 
#   summarise(totaltime=as.numeric(difftime(last(time),first(time),units = "mins"))) %>% 
#   as.numeric() %>% round(1)
session$totaltime.min <- gpx %>% 
  summarise(totaltime = round(as.numeric(last(time) - first(time))/60,1)) %>% 
  as.numeric()
session$frequency_waves.min <- round(session$totaltime.min / session$nwaves,0)
# time per wave
session$maxtime_singlewave.s <- max(wave %>% 
  filter(wave.n != 0) %>% 
  group_by(wave.n) %>% 
  summarise(wave.time = last(cum_s)-first(cum_s), .groups='drop') %>% 
  select(wave.time)) %>% 
  round(1)
session$totaltime_allwaves.s <- sum(wave %>% 
  filter(wave.n != 0) %>% 
  group_by(wave.n) %>% 
  summarise(wave.time = last(cum_s)-first(cum_s), .groups='drop') %>% 
  select(wave.time)) %>% 
  round(1)
session$averagetime_allwaves.s <- round(session$totaltime_allwaves.s / session$nwaves,0)
# distance per wave
session$maxdist_singlewave.m <- max(wave %>% 
  filter(wave.n != 0) %>% 
  group_by(wave.n) %>% 
  summarise(wave.x= last(cum_distance)-first(cum_distance), .groups='drop') %>% 
  select(wave.x)) %>% 
  round(0)
session$totaldist_allwaves.m <- sum(wave %>% 
  filter(wave.n != 0) %>% 
  group_by(wave.n) %>% 
  summarise(wave.x = last(cum_distance)-first(cum_distance), .groups='drop') %>% 
  select(wave.x)) %>% 
  round(0)
session$averagedist_allwaves.m <- round(session$totaldist_allwaves.m / session$nwaves,0)
 # session
```

# Session 1
<!-- ################ WEBSITE SETUP ############## -->
<!-- icons from https://fontawesome.com/icons?d=gallery&v=5.0.0&m=free -->

Column {.sidebar data-width=800 data-padding=10}
-------------------------------------

### 

```{r}
testmap
```

Row {data-height=100}
-------------------------------------

### Duration

```{r}
valueBox(
  value=paste(session$totaltime.min,"min")
)
```

### Total Waves

```{r}
valueBox(
  value=session$nwaves,
)
```   

Row {data-height=60}
-------------------------------------

### One wave every...

```{r}
valueBox(
  value=paste(session$frequency_waves.min,"min")
)
```   

Row {data-height=70}
-------------------------------------

### Wave distance (max)

```{r}
valueBox(
  value=paste(session$maxdist_singlewave.m,"m")
)
```  

### Wave distance (avg)

```{r}
valueBox(
  value=paste(session$averagedist_allwaves.m,"m")
)
```  

### Wave distance (total)

```{r}
valueBox(
  value=paste(session$totaldist_allwaves.m,"m")
)
```  

Row {data-height=70}
--------------------

### Wave duration (max)

```{r}
valueBox(
  value=paste0(session$maxtime_singlewave.s,"\"")
)
```  

### Wave duration (avg)

```{r}
valueBox(
  value=paste0(session$averagetime_allwaves.s,"\"")
)
```  

### Wave duration (total)

```{r}
valueBox(
  value=paste0(session$totaltime_allwaves.s,"\"")
)
```  


<!-- ##### Created by [\@RuizCSergio](http://twitter.com/RuizCSergio) -->

